config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  devise_for :users
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    get 'sign_in', to: 'devise/sessions#new', as: 'login'
  end

  resources :users
  resources :stories

  root 'static_pages#home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/story.rb
class Story < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  belongs_to :user

  attr_accessor :tag_names

  has_and_belongs_to_many :tags

  validates :title, :description, presence: true
  validates :title, uniqueness: :true

  def should_generate_new_friendly_id?
    title_changed? || super
  end

  before_create :associate_tags
  before_save :associate_tags

  private

  def associate_tags
    if tag_names
      tags.clear
      tag_names.split(' ').each do |name|
        tags << Tag.where(name: name).first_or_create
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :set_default_role, :if => :new_record?
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_attached_file :avatar, styles: { thumb: '50x50#', small: '100x100#' }
  has_many :stories

  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage/
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes
  validates :password, length: { in: 6..20 }
  validates :name, :email, :password, :password_confirmation, presence: true
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i


  def set_default_role
     self.add_role(:user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

  def authorize
    redirect_to login_path, alert: 'Not authorized!' if current_user.nil?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize, only: [:new, :edit, :update, :destroy]

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user

    if @story.save
      redirect_to @story, notice: 'Story successfully created.'
    else
      render 'edit'
    end
  end

  def edit
    @story = Story.friendly.find(params[:id])
    if current_user.id != @story.user.id
      render 'show'
    end
  end

  def update
    @story = Story.friendly.find(params[:id])

    if @story.update(story_params)
      redirect_to @story, notice: 'Story successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @story = Story.friendly.find(params[:id])

    if request.path != story_path(@story)
      redirect_to @story, status: :moved_permanently
    end
  end

  def destroy
    @story = Story.friendly.find(params[:id])
    @story.destroy
    redirect_to stories_path, notice: 'Story successfully destroyed.'
  end

  private

  def story_params
    params.require(:story).permit(:title, :description, :tag_names)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'Successfully updated'
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])

    if request.path != user_path(@user)
      redirect_to @user, status: :moved_permanently
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoupleStory
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag Ckeditor.cdn_url
    = csrf_meta_tags
  %body
    #wrapper
      %header
        .navbar
          %ul
            - if current_user
              %li
                = link_to 'Log Out', sign_out_path, :class => 'btn'
              %li
                = link_to 'Profile', user_path(current_user), :class => 'btn'
              %li{:id => :login}
                = image_tag current_user.avatar(:thumb)
                = current_user.name
            - else
              %li
                = link_to 'Sign Up', new_user_registration_path, :class => 'btn'
              %li
                = link_to 'Log In', new_user_session_path, :class => 'btn'

      .error-message
        - flash.each do |name, msg|
          = content_tag :div, msg, id: "flash_#{name}"

      .left-col
        .popular-tags
          %p Popular tags:
          %ol
            %li
              Cake
            %li
              Dick
            %li
              Dick
            %li
              Dick
            %li
              Dick
        .b-header.stories
          = link_to 'New Story', new_story_path 
          %br
          = link_to 'All Stories', stories_path

      .right-col
        %main
          = yield

      %footer
        Created by KraevRoot:
        = link_to 'https://github.com/KraevRoot', 'https://github.com/KraevRoot'

app/views/static_pages/about.html.haml
%h1 StaticPages#about
%p Find me in app/views/static_pages/about.html.haml

app/views/static_pages/help.html.haml
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.haml

app/views/static_pages/home.html.haml
%h1 StoriesHub
%p This site let you create and share your own stories with community. Everyone can contribute to your story or make new story, which will be based on yours.

app/views/stories/_form.html.haml
= simple_form_for @story do |f|
  = f.error_notification
  = f.input :title, placeholder: 'enter title'
  = f.cktext_area :description, ckeditor: {uiColor: '#C3DBE3', toolber:'mini'}
  = f.input :tag_names, placeholder: 'tags'
  = f.button :submit

= link_to 'Back', stories_path, :class => 'btn'

app/views/stories/edit.html.haml
%h2 Update story

= render 'form'

app/views/stories/index.html.haml
%p Stories:

- @stories.each do |story|
  %article
    #title
      %h1= link_to h(story.title), story
    #tags
      %h5= render story.tags
    .action-buttons
      = button_to 'edit', edit_story_path(story), :class => 'btn', :method => :get
      = button_to 'delete', story_path(story), :class => 'btn', :method => :delete, data: { confirm: 'Are you sure?' }

app/views/stories/new.html.haml
%h2 New story

= render 'form'

app/views/stories/show.html.haml
.story-show
  %h3.story_title.centered= "Title: #{h(@story.title)}"
  .story_description= raw(@story.description)
  .story_author
    Created by
    = link_to @story.user.name, user_path(:id => @story.user.id)

  = link_to 'Stories', stories_path, :class => 'btn'

  = link_to 'Edit', edit_story_path(@story), :class => 'btn'

  = link_to 'Destroy', story_path(@story), :class => 'btn',
  						method: :delete,
  						data: { confirm: 'Are you sure?' }

app/views/tags/_tag.html.haml
%span 
  .tag= tag.name

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification
  .f-input
    = f.input :name, placeholder: 'username'
  .f-input
    = f.input :email, placeholder: 'email'
  .f-input
    = f.input :password, placeholder: 'password'
  .f-input
    = f.input :password_confirmation, placeholder: 'password'
  .f-input.file
    = f.input :avatar, as: :file
  %br
  = f.button :submit

= button_to 'Back', stories_path, :class => 'btn', :method => :get

app/views/users/edit.html.haml
%h1 Update Profile
= render 'form'

app/views/users/new.html.haml
.b-registration
  %h1 Sign Up
  = render 'form'

app/views/users/show.html.haml
%h1 Profile
%p= @user.name
%p= @user.email
%p= image_tag @user.avatar(:small)

= link_to 'Stories', stories_path, :class => 'btn'
= link_to 'Edit', edit_user_path(current_user), :class => 'btn btn-warning'